stages:
  - test
  - deploy

variables:
  PYTHON_EXECUTABLE: '$PYTHON_EXECUTABLE'
  WORKON_HOME: '$WORKON_HOME'
  SECRET_KEY: '$SECRET_KEY'
  PYTHONANYWHERE_API_TOKEN: '8fb50f162002d7826b37ba0b83dc36e689ec91ea'
  DEBUG: "False"
  ALLOWED_HOSTS: "khawarkhan.pythonanywhere.com"  # Replace with your domain name test-1s 
  DB_ENGINE: "django.db.backends.sqlite3"
  DB_NAME: "db.sqlite3"
  STATIC_URL: "/static/"

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache S
cache:
  paths:
    - ~/.cache/pip/ 

before_script:
  - pip install -r requirements.txt

test:
  image: python:latest
  script:
    - cd backendcrud
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test

deploy:
  image: python:latest
  stage: deploy
  script:
    - python -m venv venv
    - chmod +x venv/bin/activate
    - source venv/bin/activate
    - pip install pythonanywhere
    - pa_autoconfigure_django.py https://github.com/khawar11/Backend_VueJs_DJANGO_CRUD.git --branch=master --domain=khawarkhan.pythonanywhere.com --python=3.8 --token=8fb50f162002d7826b37ba0b83dc36e689ec91ea --nuke
    # --token=8fb50f162002d7826b37ba0b83dc36e689ec91ea
  environment:
    name: production
    url: "https://khawarkhan.pythonanywhere.com/" 
  only:
    - master